import Head from "next/head";
import Image from "next/image";
import Navbar from "../components/Navbar/Navbar";
import Event from "../components/Event/Event";
import OverviewBox from "../components/OverviewBox/OverviewBox";
import ManureNft from "../public/images/manureNft.png";
import waterNft from "../public/images/waterNft.png";
export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />

      </Head>

      <main className="font-sans">
        <div className="px-4 ">

        <Navbar />
        </div>
        <div className="flex space-x-8 bg-[#F5F5F5] px-4">
          <div className="w-[72%] pt-6 ">
            <div className="text-[#00000080] text-[24px] pb-2">Event</div>
            
              <Event
                Name={"Manure"}
                date={"2022-09-13 08:57:15"}
                progress={44}
                failedTransaction={2}
                processingTransaction={8}
                successTransaction={44}
                key={1}
                Nft={ManureNft}
                occasion={"Harvest"}
              />
            <div className="pt-6">
              <Event
                Name={"Water"}
                date={"2022-09-13 08:57:15"}
                progress={100}
                failedTransaction={0}
                processingTransaction={0}
                successTransaction={100}
                Nft={waterNft}
                key={1}
                occasion={"it is raining"}
              />
            </div>
          </div>
          <div className="pt-6 w-1/4 pb-3">
            <div className="text-[#00000080] text-[24px] pb-2">Overview</div>
            <div className="space-y-6">
            <OverviewBox
                key={1}
                data={[
                  { item: "Wallet balance", value: '0.489 ETH' }
                ]}
              />
              <OverviewBox
                key={1}
                title={"NFTs"}
                data={[
                  { item: "NFT items", value: 187 },
                  { item: "Collections", value: 5 },
                  { item: "Minted", value: 39 },
                ]}
              />
              <OverviewBox
                key={1}
                title={"Saved Searches"}
                data={[
                  { item: "Green apple" },
                  { item: "Christmas tree" },
                ]}
              />
              <OverviewBox
                key={1}
                title={"Recent Activity"}
                data={[
                  { item: "Settings > Account" },
                  { item: "Sales reports" },
                ]}
              />
            </div>
          </div>
        </div>
      </main>
    </div>
  );
}
